/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesTaqyeemiRouteImport } from './routes/companies.taqyeemi'
import { Route as CompaniesPointpassRouteImport } from './routes/companies.pointpass'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesTaqyeemiRoute = CompaniesTaqyeemiRouteImport.update({
  id: '/companies/taqyeemi',
  path: '/companies/taqyeemi',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesPointpassRoute = CompaniesPointpassRouteImport.update({
  id: '/companies/pointpass',
  path: '/companies/pointpass',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/companies/pointpass': typeof CompaniesPointpassRoute
  '/companies/taqyeemi': typeof CompaniesTaqyeemiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/companies/pointpass': typeof CompaniesPointpassRoute
  '/companies/taqyeemi': typeof CompaniesTaqyeemiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/companies/pointpass': typeof CompaniesPointpassRoute
  '/companies/taqyeemi': typeof CompaniesTaqyeemiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/companies/pointpass'
    | '/companies/taqyeemi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/companies/pointpass'
    | '/companies/taqyeemi'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/companies/pointpass'
    | '/companies/taqyeemi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CompaniesPointpassRoute: typeof CompaniesPointpassRoute
  CompaniesTaqyeemiRoute: typeof CompaniesTaqyeemiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/taqyeemi': {
      id: '/companies/taqyeemi'
      path: '/companies/taqyeemi'
      fullPath: '/companies/taqyeemi'
      preLoaderRoute: typeof CompaniesTaqyeemiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/pointpass': {
      id: '/companies/pointpass'
      path: '/companies/pointpass'
      fullPath: '/companies/pointpass'
      preLoaderRoute: typeof CompaniesPointpassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CompaniesPointpassRoute: CompaniesPointpassRoute,
  CompaniesTaqyeemiRoute: CompaniesTaqyeemiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
