/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesTaqyeemiRouteImport } from './routes/companies.taqyeemi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesTaqyeemiRoute = CompaniesTaqyeemiRouteImport.update({
  id: '/companies/taqyeemi',
  path: '/companies/taqyeemi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/taqyeemi': typeof CompaniesTaqyeemiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/taqyeemi': typeof CompaniesTaqyeemiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies/taqyeemi': typeof CompaniesTaqyeemiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/companies/taqyeemi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/companies/taqyeemi'
  id: '__root__' | '/' | '/companies/taqyeemi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesTaqyeemiRoute: typeof CompaniesTaqyeemiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/taqyeemi': {
      id: '/companies/taqyeemi'
      path: '/companies/taqyeemi'
      fullPath: '/companies/taqyeemi'
      preLoaderRoute: typeof CompaniesTaqyeemiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesTaqyeemiRoute: CompaniesTaqyeemiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
